In [16]:
from __future__ import annotations

import re
import math
import json
from dataclasses import dataclass, field
from datetime import datetime
from collections import Counter, defaultdict
from typing import List, Dict, Any, Optional, Tuple


# =========================
# 1. MOCK DATA
# =========================

DOCUMENTS = [
    {
        "doc_id": "inv_001",
        "doc_type": "invoice",
        "vendor": "Adobe",
        "vendor_normalized": "adobe",
        "invoice_number": "ADB-2024-04-1182",
        "invoice_date": "2024-04-12",
        "currency": "USD",
        "subtotal": 89.99,
        "tax": 0.00,
        "total": 89.99,
        "status": "paid",
        "line_items": [
            {"description": "Creative Cloud Teams April 2024", "qty": 1, "unit_price": 89.99, "line_total": 89.99}
        ],
        "raw_text": "Adobe Creative Cloud Teams April 2024 invoice total 89.99 USD paid"
    },
    {
        "doc_id": "inv_002",
        "doc_type": "invoice",
        "vendor": "Adobe",
        "vendor_normalized": "adobe",
        "invoice_number": "ADB-2025-03-7714",
        "invoice_date": "2025-03-09",
        "currency": "USD",
        "subtotal": 104.99,
        "tax": 0.00,
        "total": 104.99,
        "status": "paid",
        "line_items": [
            {"description": "Creative Cloud Teams March 2025", "qty": 1, "unit_price": 104.99, "line_total": 104.99}
        ],
        "raw_text": "Adobe Creative Cloud Teams March 2025 invoice total 104.99 USD paid"
    },
    {
        "doc_id": "rcpt_003",
        "doc_type": "receipt",
        "vendor": "Athens Office Supplies",
        "vendor_normalized": "athens office supplies",
        "invoice_number": None,
        "invoice_date": "2025-03-10",
        "currency": "EUR",
        "subtotal": 42.50,
        "tax": 10.20,
        "total": 52.70,
        "status": "captured",
        "line_items": [
            {"description": "Printer paper A4", "qty": 5, "unit_price": 5.00, "line_total": 25.00},
            {"description": "Black ink cartridge", "qty": 1, "unit_price": 17.50, "line_total": 17.50}
        ],
        "raw_text": "Athens Office Supplies receipt printer paper black ink cartridge total 52.70 EUR"
    },
    {
        "doc_id": "inv_004",
        "doc_type": "invoice",
        "vendor": "Figma",
        "vendor_normalized": "figma",
        "invoice_number": "FIG-2025-03-9912",
        "invoice_date": "2025-03-15",
        "currency": "USD",
        "subtotal": 75.00,
        "tax": 0.00,
        "total": 75.00,
        "status": "paid",
        "line_items": [
            {"description": "Figma Professional Plan", "qty": 3, "unit_price": 25.00, "line_total": 75.00}
        ],
        "raw_text": "Figma Professional Plan March 2025 invoice total 75.00 USD"
    },
]


# =========================
# 2. HELPERS
# =========================

MONTHS = {
    "january": 1, "february": 2, "march": 3, "april": 4,
    "may": 5, "june": 6, "july": 7, "august": 8,
    "september": 9, "october": 10, "november": 11, "december": 12
}

KNOWN_VENDORS = {
    "adobe": "Adobe",
    "figma": "Figma",
    "athens office supplies": "Athens Office Supplies",
}

STOPWORDS = {
    "show", "me", "find", "the", "a", "an", "from", "for", "of", "in",
    "all", "with", "documents", "document", "please", "get"
}


def tokenize(text: str) -> List[str]:
    return re.findall(r"[a-zA-Z0-9\.]+", text.lower())


def parse_date(date_str: str) -> datetime:
    return datetime.strptime(date_str, "%Y-%m-%d")


def month_range(year: int, month: int) -> Tuple[str, str]:
    start = datetime(year, month, 1)
    if month == 12:
        end = datetime(year + 1, 1, 1)
    else:
        end = datetime(year, month + 1, 1)
    return start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")


def normalize_vendor(text: str) -> Optional[str]:
    text_l = text.lower()
    for vendor_key, vendor_display in KNOWN_VENDORS.items():
        if vendor_key in text_l:
            return vendor_display
    return None


# =========================
# 3. QUERY PARSER
# =========================

def parse_user_query(query: str) -> Dict[str, Any]:
    """
    This stands in for a cheap LLM parser.
    In production, you can replace this with an LLM call that returns JSON.
    """
    q = query.lower()

    result = {
        "intent": "search_documents",
        "semantic_query": "",
        "filters": {
            "doc_type": None,
            "vendor_normalized": None,
            "date_start": None,
            "date_end": None,
            "currency": None,
            "amount_gt": None,
            "amount_lt": None,
            "invoice_number": None,
        }
    }

    # doc type
    if "invoice" in q:
        result["filters"]["doc_type"] = "invoice"
    elif "receipt" in q:
        result["filters"]["doc_type"] = "receipt"

    # vendor
    vendor = normalize_vendor(q)
    if vendor:
        result["filters"]["vendor_normalized"] = vendor.lower()

    # invoice number pattern
    inv_match = re.search(r"\b[a-z]{2,5}-\d{4}-\d{2}-\d{3,6}\b", q, re.I)
    if inv_match:
        result["filters"]["invoice_number"] = inv_match.group(0).upper()

    # month + year
    month_match = re.search(
        r"\b(january|february|march|april|may|june|july|august|september|october|november|december)\s+(\d{4})\b",
        q
    )
    if month_match:
        month_name = month_match.group(1)
        year = int(month_match.group(2))
        month = MONTHS[month_name]
        start, end = month_range(year, month)
        result["filters"]["date_start"] = start
        result["filters"]["date_end"] = end

    # amount filters
    gt_match = re.search(r"(over|greater than|above)\s*[$€]?(\d+(?:\.\d+)?)", q)
    lt_match = re.search(r"(under|less than|below)\s*[$€]?(\d+(?:\.\d+)?)", q)

    if gt_match:
        result["filters"]["amount_gt"] = float(gt_match.group(2))
    if lt_match:
        result["filters"]["amount_lt"] = float(lt_match.group(2))

    # currency
    if "$" in q or "usd" in q or "dollar" in q:
        result["filters"]["currency"] = "USD"
    elif "€" in q or "eur" in q or "euro" in q:
        result["filters"]["currency"] = "EUR"

    # semantic terms = leftover meaningful tokens
    tokens = tokenize(q)
    ignored = set(STOPWORDS) | set(MONTHS.keys()) | {
        "invoice", "receipt", "usd", "eur", "dollar", "dollars", "euro", "euros",
        "over", "greater", "than", "above", "under", "less", "below"
    }
    semantic_terms = [t for t in tokens if t not in ignored and not t.isdigit()]
    result["semantic_query"] = " ".join(semantic_terms)

    return result


# =========================
# 4. METADATA FILTERING
# =========================

def metadata_filter(docs: List[Dict[str, Any]], filters: Dict[str, Any]) -> List[Dict[str, Any]]:
    filtered = []

    for doc in docs:
        if filters.get("doc_type") and doc["doc_type"] != filters["doc_type"]:
            continue

        if filters.get("vendor_normalized") and doc["vendor_normalized"] != filters["vendor_normalized"]:
            continue

        if filters.get("invoice_number") and doc.get("invoice_number") != filters["invoice_number"]:
            continue

        if filters.get("currency") and doc["currency"] != filters["currency"]:
            continue

        if filters.get("amount_gt") is not None and doc["total"] <= filters["amount_gt"]:
            continue

        if filters.get("amount_lt") is not None and doc["total"] >= filters["amount_lt"]:
            continue

        doc_date = parse_date(doc["invoice_date"])
        if filters.get("date_start"):
            if doc_date < parse_date(filters["date_start"]):
                continue
        if filters.get("date_end"):
            if doc_date >= parse_date(filters["date_end"]):
                continue

        filtered.append(doc)

    return filtered


# =========================
# 5. BM25-LIKE LEXICAL SEARCH
# =========================

class SimpleBM25:
    def __init__(self, docs: List[Dict[str, Any]], text_key: str = "raw_text"):
        self.docs = docs
        self.text_key = text_key
        self.k1 = 1.5
        self.b = 0.75

        self.doc_tokens = []
        self.doc_freq = defaultdict(int)
        self.doc_lens = []

        for doc in docs:
            tokens = tokenize(doc[text_key])
            self.doc_tokens.append(tokens)
            self.doc_lens.append(len(tokens))
            unique_tokens = set(tokens)
            for tok in unique_tokens:
                self.doc_freq[tok] += 1

        self.N = len(docs)
        self.avgdl = sum(self.doc_lens) / max(self.N, 1)

    def idf(self, term: str) -> float:
        n_qi = self.doc_freq.get(term, 0)
        return math.log(1 + (self.N - n_qi + 0.5) / (n_qi + 0.5))

    def score(self, query: str, doc_index: int) -> float:
        query_terms = tokenize(query)
        tf = Counter(self.doc_tokens[doc_index])
        dl = self.doc_lens[doc_index]
        score = 0.0

        for term in query_terms:
            if term not in tf:
                continue
            freq = tf[term]
            numerator = freq * (self.k1 + 1)
            denominator = freq + self.k1 * (1 - self.b + self.b * dl / self.avgdl)
            score += self.idf(term) * numerator / denominator

        return score


# =========================
# 6. SIMPLE VECTOR-LIKE SCORING
# =========================

def text_to_vector(text: str) -> Counter:
    return Counter(tokenize(text))


def cosine_sim(a: Counter, b: Counter) -> float:
    keys = set(a) | set(b)
    dot = sum(a[k] * b[k] for k in keys)
    na = math.sqrt(sum(v * v for v in a.values()))
    nb = math.sqrt(sum(v * v for v in b.values()))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


# =========================
# 7. RECIPROCAL RANK FUSION
# =========================

def reciprocal_rank_fusion(rankings: List[List[str]], k: int = 60) -> Dict[str, float]:
    scores = defaultdict(float)
    for ranking in rankings:
        for rank, doc_id in enumerate(ranking, start=1):
            scores[doc_id] += 1.0 / (k + rank)
    return dict(scores)


# =========================
# 8. RETRIEVAL PIPELINE
# =========================

def hybrid_retrieve(user_query: str, docs: List[Dict[str, Any]], top_k: int = 5) -> Dict[str, Any]:
    parsed = parse_user_query(user_query)

    # Step 1: hard filters
    filtered_docs = metadata_filter(docs, parsed["filters"])

    if not filtered_docs:
        return {
            "parsed_query": parsed,
            "results": [],
            "message": "No documents matched the structured filters."
        }

    # Step 2: BM25 on filtered set
    bm25 = SimpleBM25(filtered_docs)
    bm25_scored = []
    for i, doc in enumerate(filtered_docs):
        score = bm25.score(parsed["semantic_query"] or user_query, i)
        bm25_scored.append((doc["doc_id"], score))

    bm25_scored.sort(key=lambda x: x[1], reverse=True)
    bm25_ranked_ids = [doc_id for doc_id, _ in bm25_scored]

    # Step 3: vector-like scoring on filtered set
    q_vec = text_to_vector(parsed["semantic_query"] or user_query)
    vec_scored = []
    for doc in filtered_docs:
        d_vec = text_to_vector(doc["raw_text"])
        score = cosine_sim(q_vec, d_vec)
        vec_scored.append((doc["doc_id"], score))

    vec_scored.sort(key=lambda x: x[1], reverse=True)
    vec_ranked_ids = [doc_id for doc_id, _ in vec_scored]

    # Step 4: fuse ranks
    fused_scores = reciprocal_rank_fusion([bm25_ranked_ids, vec_ranked_ids])

    # Step 5: assemble final results
    id_to_doc = {d["doc_id"]: d for d in filtered_docs}
    ranked = sorted(fused_scores.items(), key=lambda x: x[1], reverse=True)[:top_k]

    results = []
    for doc_id, fused_score in ranked:
        bm25_score = next((s for d, s in bm25_scored if d == doc_id), 0.0)
        vec_score = next((s for d, s in vec_scored if d == doc_id), 0.0)
        results.append({
            "doc": id_to_doc[doc_id],
            "scores": {
                "bm25": round(bm25_score, 4),
                "vector": round(vec_score, 4),
                "rrf": round(fused_score, 6),
            }
        })

    return {
        "parsed_query": parsed,
        "results": results
    }


# =========================
# 9. ANSWER GENERATOR
# =========================

def answer_from_results(user_query: str, retrieval_output: Dict[str, Any]) -> str:
    results = retrieval_output["results"]

    if not results:
        return "I could not find any documents that matched the structured filters in your query."

    lines = []
    lines.append(f"Query: {user_query}")
    lines.append("Matched documents:")

    for r in results:
        d = r["doc"]
        lines.append(
            f"- {d['doc_id']}: {d['vendor']} {d['doc_type']} dated {d['invoice_date']} "
            f"for {d['total']} {d['currency']} "
            f"(BM25={r['scores']['bm25']}, Vector={r['scores']['vector']}, RRF={r['scores']['rrf']})"
        )

    top = results[0]["doc"]
    lines.append(
        f"\nBest match: {top['doc_id']} ({top['vendor']}, {top['invoice_date']}, "
        f"{top['total']} {top['currency']})"
    )

    return "\n".join(lines)


# =========================
# 10. DEMO
# =========================

if __name__ == "__main__":
    queries = [
        "Find the Adobe invoice from March 2025",
        "Show me Adobe invoices from March 2025 over $100",
        "Find the receipt for printer paper in euros",
        "Get invoice ADB-2025-03-7714",
        "What's the weather"
    ]

    for q in queries:
        print("=" * 80)
        print("USER QUERY:", q)

        out = hybrid_retrieve(q, DOCUMENTS, top_k=3)

        print("\nPARSED QUERY:")
        print(json.dumps(out["parsed_query"], indent=2))

        print("\nANSWER:")
        print(answer_from_results(q, out))
        print()

================================================================================

USER QUERY: Find the Adobe invoice from March 2025

PARSED QUERY:

{
  "intent": "search_documents",
  "semantic_query": "adobe",
  "filters": {
    "doc_type": "invoice",
    "vendor_normalized": "adobe",
    "date_start": "2025-03-01",
    "date_end": "2025-04-01",
    "currency": null,
    "amount_gt": null,
    "amount_lt": null,
    "invoice_number": null
  }
}

ANSWER:

Query: Find the Adobe invoice from March 2025
Matched documents:
- inv_002: Adobe invoice dated 2025-03-09 for 104.99 USD (BM25=0.2877, Vector=0.3015, RRF=0.032787)

Best match: inv_002 (Adobe, 2025-03-09, 104.99 USD)

================================================================================

USER QUERY: Show me Adobe invoices from March 2025 over $100

PARSED QUERY:

{
  "intent": "search_documents",
  "semantic_query": "adobe invoices",
  "filters": {
    "doc_type": "invoice",
    "vendor_normalized": "adobe",
    "date_start": "2025-03-01",
    "date_end": "2025-04-01",
    "currency": "USD",
    "amount_gt": 100.0,
    "amount_lt": null,
    "invoice_number": null
  }
}

ANSWER:

Query: Show me Adobe invoices from March 2025 over $100
Matched documents:
- inv_002: Adobe invoice dated 2025-03-09 for 104.99 USD (BM25=0.2877, Vector=0.2132, RRF=0.032787)

Best match: inv_002 (Adobe, 2025-03-09, 104.99 USD)

================================================================================

USER QUERY: Find the receipt for printer paper in euros

PARSED QUERY:

{
  "intent": "search_documents",
  "semantic_query": "printer paper",
  "filters": {
    "doc_type": "receipt",
    "vendor_normalized": null,
    "date_start": null,
    "date_end": null,
    "currency": "EUR",
    "amount_gt": null,
    "amount_lt": null,
    "invoice_number": null
  }
}

ANSWER:

Query: Find the receipt for printer paper in euros
Matched documents:
- rcpt_003: Athens Office Supplies receipt dated 2025-03-10 for 52.7 EUR (BM25=0.5754, Vector=0.4082, RRF=0.032787)

Best match: rcpt_003 (Athens Office Supplies, 2025-03-10, 52.7 EUR)

================================================================================

USER QUERY: Get invoice ADB-2025-03-7714

PARSED QUERY:

{
  "intent": "search_documents",
  "semantic_query": "adb",
  "filters": {
    "doc_type": "invoice",
    "vendor_normalized": null,
    "date_start": null,
    "date_end": null,
    "currency": null,
    "amount_gt": null,
    "amount_lt": null,
    "invoice_number": "ADB-2025-03-7714"
  }
}

ANSWER:

Query: Get invoice ADB-2025-03-7714
Matched documents:
- inv_002: Adobe invoice dated 2025-03-09 for 104.99 USD (BM25=0.0, Vector=0.0, RRF=0.032787)

Best match: inv_002 (Adobe, 2025-03-09, 104.99 USD)

================================================================================

USER QUERY: What's the weather

PARSED QUERY:

{
  "intent": "search_documents",
  "semantic_query": "what s weather",
  "filters": {
    "doc_type": null,
    "vendor_normalized": null,
    "date_start": null,
    "date_end": null,
    "currency": null,
    "amount_gt": null,
    "amount_lt": null,
    "invoice_number": null
  }
}

ANSWER:

Query: What's the weather
Matched documents:
- inv_001: Adobe invoice dated 2024-04-12 for 89.99 USD (BM25=0.0, Vector=0.0, RRF=0.032787)
- inv_002: Adobe invoice dated 2025-03-09 for 104.99 USD (BM25=0.0, Vector=0.0, RRF=0.032258)
- rcpt_003: Athens Office Supplies receipt dated 2025-03-10 for 52.7 EUR (BM25=0.0, Vector=0.0, RRF=0.031746)

Best match: inv_001 (Adobe, 2024-04-12, 89.99 USD)

In [34]:
from google import genai



client = genai.Client(api_key="AIzaSyC7CORyHMCN_0l_-bQPJBti-GLejgOY7uk")


def call_daisy(prompt):
    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=prompt,
    )
    
    return response

# print(response.text)

In [46]:
PROMPT = (
    "You are a strict information-extraction referee.\n\n"
    "Your job is to validate whether a parsed finance query matches the original user request.\n"
    "You will receive:\n"
    "1. the original user prompt\n"
    "2. the parser output JSON\n\n"
    "You must compare the parser output against the user prompt and determine whether each extracted field is correct.\n\n"
    "Rules:\n"
    "- Be conservative.\n"
    "- Do not invent values that are not clearly supported by the user prompt.\n"
    "- If a field is missing from the user prompt, it must be null.\n"
    "- If a field in the parser output is wrong, fix it.\n"
    "- Keep normalized values where appropriate, for example:\n"
    "  - doc_type should be things like \"invoice\" or \"receipt\"\n"
    "  - vendor_normalized should be a normalized vendor/company string if clearly present\n"
    "  - currency should be a 3-letter code like \"USD\" or \"EUR\"\n"
    "- Preserve the intended schema exactly.\n"
    "- Return JSON only.\n"
    "- No markdown.\n"
    "- No explanation text outside JSON.\n\n"
    "Expected output schema:\n"
    "{\n"
    "  \"is_valid\": true,\n"
    "  \"errors\": [],\n"
    "  \"corrected\": {\n"
    "    \"intent\": \"search_documents\",\n"
    "    \"semantic_query\": \"\",\n"
    "    \"filters\": {\n"
    "      \"doc_type\": null,\n"
    "      \"vendor_normalized\": null,\n"
    "      \"date_start\": null,\n"
    "      \"date_end\": null,\n"
    "      \"currency\": null,\n"
    "      \"amount_gt\": null,\n"
    "      \"amount_lt\": null,\n"
    "      \"invoice_number\": null\n"
    "    }\n"
    "  },\n"
    "  \"field_checks\": {\n"
    "    \"intent\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"semantic_query\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.doc_type\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.vendor_normalized\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.date_start\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.date_end\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.currency\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.amount_gt\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.amount_lt\": {\"ok\": true, \"reason\": \"\"},\n"
    "    \"filters.invoice_number\": {\"ok\": true, \"reason\": \"\"}\n"
    "  }\n"
    "}\n\n"
    "Validation policy:\n"
    "- \"is_valid\" is true only if all extracted fields are correct.\n"
    "- \"errors\" should contain short machine-readable error codes, for example:\n"
    "  [\"wrong_doc_type\", \"missing_date_start\", \"wrong_vendor\"]\n"
    "- \"corrected\" must contain the best corrected parse based only on the user prompt.\n"
    "- \"semantic_query\" should contain only leftover meaningful search terms not already represented in structured filters.\n"
    "- If the user prompt implies a date range like \"between 2026-01-01 and 2026-03-31\", extract both date_start and date_end exactly.\n"
    "- If the prompt mentions \"company X\", that may indicate a vendor/company filter if your normalization logic supports it.\n"
    "- If a value is uncertain, set it to null and mark the relevant field check as not ok.\n\n"
    "Original user prompt:\n"
    f"{text}\n\n"
    "Parser output JSON:\n"
    f"{json.dumps(parse_user_query(result['sequence']))}"
)

In [36]:
from transformers import pipeline
from rich import print
import json

classifier = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/ModernBERT-large-zeroshot-v2.0"
)

Loading weights: 100%|██████████| 174/174 [00:00<00:00, 7825.03it/s]

In [49]:

text = ["Give invoice for company X between the dates 2026-01-01 and 2026-03-31"]

finance_prompts = [
    "Generate an invoice for company X between 2026-01-01 and 2026-03-31.",
    "Show the total revenue for product Y in Q1 2026.",
    "Send me the bank statement for account 12345 from last month.",
    "Categorize this transaction as travel, office supplies, or salary.",
    "What is the current balance on my credit card ending in 7890?",
    "Calculate the VAT amount for this invoice of 1000 EUR.",
    "Export the list of unpaid invoices to CSV.",
    "Create a budget for the marketing department for 2026.",
    "Tell me how much we spent on cloud hosting in April.",
    "Send a reminder email to client Z about their overdue payment."
]

non_finance_prompts = [
    "Write a short story about a cat in Athens.",
    "Give me ideas for a birthday party for my child.",
    "What are the best restaurants in downtown Athens?",
    "Draft an email to my friend about meeting for coffee.",
    "Explain how photosynthesis works in simple terms."
]

results = classifier(
    finance_prompts,
    candidate_labels=["finance", "non-finance"],
    hypothesis_template="This request is about {}."
)

for result in results:
    print(result)

{
    'sequence': 'Generate an invoice for company X between 2026-01-01 and 2026-03-31.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9972423911094666, 0.002757622627541423]
}

{
    'sequence': 'Show the total revenue for product Y in Q1 2026.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9905874133110046, 0.009412589482963085]
}

{
    'sequence': 'Send me the bank statement for account 12345 from last month.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9954615235328674, 0.004538431763648987]
}

{
    'sequence': 'Categorize this transaction as travel, office supplies, or salary.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9704646468162537, 0.029535338282585144]
}

{
    'sequence': 'What is the current balance on my credit card ending in 7890?',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9992445707321167, 0.0007554056355729699]
}

{
    'sequence': 'Calculate the VAT amount for this invoice of 1000 EUR.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9972423911094666, 0.002757622394710779]
}

{
    'sequence': 'Export the list of unpaid invoices to CSV.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9738443493843079, 0.026155618950724602]
}

{
    'sequence': 'Create a budget for the marketing department for 2026.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.997065007686615, 0.002934951800853014]
}

{
    'sequence': 'Tell me how much we spent on cloud hosting in April.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9648551344871521, 0.03514484316110611]
}

{
    'sequence': 'Send a reminder email to client Z about their overdue payment.',
    'labels': ['finance', 'non-finance'],
    'scores': [0.9755769371986389, 0.02442309446632862]
}

In [48]:
for result in results:
    if result['labels'][0] == 'non-finance':
        print("User invalid prompt")
    else:
        print(parse_user_query(result['sequence']))

{
    'intent': 'search_documents',
    'semantic_query': 'give company x between dates and',
    'filters': {
        'doc_type': 'invoice',
        'vendor_normalized': None,
        'date_start': None,
        'date_end': None,
        'currency': None,
        'amount_gt': None,
        'amount_lt': None,
        'invoice_number': None
    }
}

In [41]:
example_1 = call_daisy(PROMPT)

In [45]:
json.loads(example_1.text)

{'is_valid': False,
 'errors': ['wrong_semantic_query',
  'missing_doc_type',
  'missing_vendor',
  'missing_date_start',
  'missing_date_end'],
 'corrected': {'intent': 'search_documents',
  'semantic_query': '',
  'filters': {'doc_type': 'invoice',
   'vendor_normalized': 'Company X',
   'date_start': '2026-01-01',
   'date_end': '2026-03-31',
   'currency': None,
   'amount_gt': None,
   'amount_lt': None,
   'invoice_number': None}},
 'field_checks': {'intent': {'ok': True, 'reason': ''},
  'semantic_query': {'ok': False,
   'reason': 'The parser output semantic query contains hallucinated text about reminder emails not present in the prompt.'},
  'filters.doc_type': {'ok': False,
   'reason': "The user explicitly requested an 'invoice'."},
  'filters.vendor_normalized': {'ok': False,
   'reason': "The user specified 'company X'."},
  'filters.date_start': {'ok': False,
   'reason': 'The user specified 2026-01-01.'},
  'filters.date_end': {'ok': False,
   'reason': 'The user specified 2026-03-31.'},
  'filters.currency': {'ok': True, 'reason': ''},
  'filters.amount_gt': {'ok': True, 'reason': ''},
  'filters.amount_lt': {'ok': True, 'reason': ''},
  'filters.invoice_number': {'ok': True, 'reason': ''}}}

# rag dataset preparation

In [50]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("osamahosamabdellatif/high-quality-invoice-images-for-ocr")

print("Path to dataset files:", path)

Downloading to /home/uplong/.cache/kagglehub/datasets/osamahosamabdellatif/high-quality-invoice-images-for-ocr/3.archive...

100%|██████████| 1.14G/1.14G [01:18<00:00, 15.6MB/s]

Extracting files...

Path to dataset files:
/home/uplong/.cache/kagglehub/datasets/osamahosamabdellatif/high-quality-invoice-images-for-ocr/versions/3

In [65]:
from datetime import datetime
from decimal import Decimal, InvalidOperation
import json
import re


def normalize_invoice(data: dict) -> dict:
    invoice = data.get("invoice", {}) or {}
    items = data.get("items", []) or []
    subtotal_data = data.get("subtotal", {}) or {}
    payment = data.get("payment_instructions", {}) or {}

    def clean_string(value):
        if value is None:
            return None
        value = str(value).strip()
        return value if value else None

    def to_decimal(value):
        value = clean_string(value)
        if value is None:
            return None
        try:
            cleaned = value.replace(",", "")
            return Decimal(cleaned)
        except (InvalidOperation, ValueError):
            return None

    def to_float(value):
        dec = to_decimal(value)
        return float(dec) if dec is not None else None

    def to_iso_date(value):
        value = clean_string(value)
        if not value:
            return None

        for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m-%d-%Y"):
            try:
                return datetime.strptime(value, fmt).date().isoformat()
            except ValueError:
                pass

        try:
            return datetime.fromisoformat(value).date().isoformat()
        except ValueError:
            return None

    def normalize_vendor_name(name):
        name = clean_string(name)
        if not name:
            return None
        normalized = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
        return normalized or None

    vendor = clean_string(invoice.get("seller_name"))
    invoice_number = clean_string(invoice.get("invoice_number"))
    invoice_date = to_iso_date(invoice.get("invoice_date"))
    due_date = to_iso_date(invoice.get("due_date") or payment.get("due_date"))
    description = json.dumps(invoice)

    tax = to_float(subtotal_data.get("tax"))
    discount = to_float(subtotal_data.get("discount")) or 0.0
    total = to_float(subtotal_data.get("total"))

    computed_subtotal = None
    if total is not None:
        computed_subtotal = round(total - (tax or 0.0) + discount, 2)
        
    

    line_items = []
    for item in items:
        qty = to_float(item.get("quantity"))
        line_total = to_float(item.get("total_price"))
        unit_price = round(line_total / qty, 2) if qty and line_total is not None else None

        line_items.append({
            "description": clean_string(item.get("description")),
            "qty": qty,
            "unit_price": unit_price,
            "line_total": line_total
        })

    result = {
        "doc_id": f"inv_{invoice_number}" if invoice_number else "inv_unknown",
        "doc_type": "invoice",
        "vendor": vendor,
        "vendor_normalized": normalize_vendor_name(vendor),
        "invoice_number": invoice_number,
        "invoice_date": invoice_date,
        "due_date": due_date,
        "currency": "USD",
        "subtotal": computed_subtotal,
        "tax": tax if tax is not None else 0.0,
        "total": total,
        "status": "open" if due_date else "unknown",
        "line_items": line_items,
        "raw_text": description
    }

    return result

In [96]:
import pandas as pd


df = pd.read_csv(path+'/batch_1/batch_1/batch1_1.csv')    #/home/uplong/.cache/kagglehub/datasets/osamahosamabdellatif/high-quality-invoice-images-for-ocr/versions/3/batch_1/batch_1

sample = df.iloc[100]['Json Data']

print(sample.strip())

{
  "invoice": {
    "client_name": "Palmer, Chan and Salazar",
    "client_address": "492 Turner Mountains\nJesushaven, NC 39447",
    "seller_name": "Johnson, Buckley and Terry",
    "seller_address": "Unit 5000 Box 4525\nDPO AP 19517",
    "invoice_number": "58051696",
    "invoice_date": "11/05/2019",
    "due_date": ""
  },
  "items": [
    {
      "description": "Care & Repair of Furniture",
      "quantity": "1.00",
      "total_price": "4.68"
    },
    {
      "description": "Lot of 3 - Major Genealogical Record Sources LDS Mormon UK - Welsh Patronymics",
      "quantity": "1.00",
      "total_price": "8.75"
    },
    {
      "description": "The Fifty Greatest Conspiracies of All Time History s Biggest Myster",
      "quantity": "1.00",
      "total_price": "4.94"
    },
    {
      "description": "The Elf on the Shelf: A Christmas Tradition",
      "quantity": "4.00",
      "total_price": "35.60"
    }
  ],
  "subtotal": {
    "tax": "4.91",
    "discount": "",
    "total": "53.96"
  },
  "payment_instructions": {
    "due_date": "",
    "bank_name": "",
    "account_number": "GB25SPFW99639143077581",
    "payment_method": ""
  }
}

In [97]:
df

,File Name,Json Data,OCRed Text
0,batch1-0494.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Clark...",Invoice no: 84652373 Date of issue: 02/23/2021...
1,batch1-0489.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Willi...",Invoice no: 37451664 Date of issue: 06/11/2020...
2,batch1-0499.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Heste...",Invoice no: 40108666 Date of issue: 02/07/2020...
3,batch1-0497.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Olson...",Invoice no: 73285932 Date of issue: 07/25/2017...
4,batch1-0081.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Wilso...",Invoice no: 15288019 Date of issue: 09/07/2014...
...,...,...,...
494,batch1-0374.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Marti...",Invoice no: 87873157 Date of issue: 05/09/2017...
495,batch1-0359.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Smith...",Invoice no: 29534383 Date of issue: 05/30/2017...
496,batch1-0452.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Branc...",Invoice no: 77715322 Date of issue: 08/23/2013...
497,batch1-0327.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Holla...",Invoice no: 35163496 Date of issue: 10/28/2019...
498,batch1-0118.jpg,"\n{\n ""invoice"": {\n ""client_name"": ""Ellis...",Invoice no: 68766191 Date of issue: 09/26/2012...

In [98]:
normalize_invoice(json.loads(sample.strip()))

{'doc_id': 'inv_58051696',
 'doc_type': 'invoice',
 'vendor': 'Johnson, Buckley and Terry',
 'vendor_normalized': 'johnson_buckley_and_terry',
 'invoice_number': '58051696',
 'invoice_date': '2019-11-05',
 'due_date': None,
 'currency': 'USD',
 'subtotal': 49.05,
 'tax': 4.91,
 'total': 53.96,
 'status': 'unknown',
 'line_items': [{'description': 'Care & Repair of Furniture',
   'qty': 1.0,
   'unit_price': 4.68,
   'line_total': 4.68},
  {'description': 'Lot of 3 - Major Genealogical Record Sources LDS Mormon UK - Welsh Patronymics',
   'qty': 1.0,
   'unit_price': 8.75,
   'line_total': 8.75},
  {'description': 'The Fifty Greatest Conspiracies of All Time History s Biggest Myster',
   'qty': 1.0,
   'unit_price': 4.94,
   'line_total': 4.94},
  {'description': 'The Elf on the Shelf: A Christmas Tradition',
   'qty': 4.0,
   'unit_price': 8.9,
   'line_total': 35.6}],
 'raw_text': '{"client_name": "Palmer, Chan and Salazar", "client_address": "492 Turner Mountains\\nJesushaven, NC 39447", "seller_name": "Johnson, Buckley and Terry", "seller_address": "Unit 5000 Box 4525\\nDPO AP 19517", "invoice_number": "58051696", "invoice_date": "11/05/2019", "due_date": ""}'}

In [76]:
test = df['Json Data'].apply(lambda x: normalize_invoice(json.loads(x.strip())))

In [89]:
import pandas as pd
import json

import pandas as pd
import json

def series_json_to_df(s: pd.Series) -> pd.DataFrame:
    def parse(x):
        if pd.isna(x):
            return {}
        if isinstance(x, dict):
            return x
        if isinstance(x, str):
            return json.loads(x)
        return x

    return pd.json_normalize(s.map(parse), max_level=0)


new_df = series_json_to_df(test)

new_df['filename'] = df['File Name']

new_df = new_df.loc[:, ['filename', 'doc_id',
 'doc_type',
 'vendor',
 'vendor_normalized',
 'invoice_number',
 'invoice_date',
 'due_date',
 'currency',
 'subtotal',
 'tax',
 'total',
 'status',
 'line_items',
 'raw_text',
 ]]

In [90]:
new_df

,filename,doc_id,doc_type,vendor,vendor_normalized,invoice_number,invoice_date,due_date,currency,subtotal,tax,total,status,line_items,raw_text
0,batch1-0494.jpg,inv_84652373,invoice,Nguyen-Roach,nguyen_roach,84652373,2021-02-23,None,USD,211.77,21.18,232.95,unknown,[{'description': 'Stemware Rack Display Kitche...,"{""client_name"": ""Clark-Foster"", ""client_addres..."
1,batch1-0489.jpg,inv_37451664,invoice,Scott-Howard,scott_howard,37451664,2020-06-11,None,USD,139.93,13.99,153.92,unknown,[{'description': 'PUMA Boys Youth Universal FG...,"{""client_name"": ""Williams, Schneider and Gomez..."
2,batch1-0499.jpg,inv_40108666,invoice,"Bailey, Murray and Lewis",bailey_murray_and_lewis,40108666,2020-02-07,None,USD,452.92,45.29,498.21,unknown,[{'description': 'Microsoft Xbox One 1 - 500 G...,"{""client_name"": ""Hester Inc"", ""client_address""..."
3,batch1-0497.jpg,inv_73285932,invoice,"Merritt, Williams and Young",merritt_williams_and_young,73285932,2017-07-25,None,USD,615.88,61.59,677.47,unknown,[{'description': 'Bcbgeneration Black Sleevele...,"{""client_name"": ""Olson, Cisneros and Moore"", ""..."
4,batch1-0081.jpg,inv_15288019,invoice,Fernandez Ltd,fernandez_ltd,15288019,2014-09-07,None,USD,1.55,0.16,1.71,unknown,[{'description': 'Easy No Tie Rubber Shoe Lace...,"{""client_name"": ""Wilson-Wilson"", ""client_addre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,batch1-0374.jpg,inv_87873157,invoice,Kirby Group,kirby_group,87873157,2017-05-09,None,USD,600.00,60.00,660.00,unknown,[{'description': 'New Never Used CROFTON CHEFS...,"{""client_name"": ""Martin-Allison"", ""client_addr..."
495,batch1-0359.jpg,inv_29534383,invoice,"Cook, Bartlett and Giles",cook_bartlett_and_giles,29534383,2017-05-30,None,USD,329.34,32.93,362.27,unknown,[{'description': 'Lilly Pulitzer XS Spike the ...,"{""client_name"": ""Smith, Herrera and Graves"", ""..."
496,batch1-0452.jpg,inv_77715322,invoice,Pena-Boyd,pena_boyd,77715322,2013-08-23,None,USD,35.94,3.59,39.53,unknown,"[{'description': 'Lives of the Artists, Vol. 2...","{""client_name"": ""Branch-White"", ""client_addres..."
497,batch1-0327.jpg,inv_35163496,invoice,"Mcpherson, Stark and Rodriguez",mcpherson_stark_and_rodriguez,35163496,2019-10-28,None,USD,72009.00,7201.00,79210.00,unknown,[{'description': 'Lily Pulitzer Beach Fit & Fl...,"{""client_name"": ""Holland LLC"", ""client_address..."
498,batch1-0118.jpg,inv_68766191,invoice,Campbell LLC,campbell_llc,68766191,2012-09-26,None,USD,3379.69,337.97,3717.66,unknown,[{'description': 'Xbox One X 1 TB Console w/ W...,"{""client_name"": ""Ellison-Simpson"", ""client_add..."